@startuml
class Persona {
    - String nombre
    - String apellidos
    - String dni
    - int añoNacimiento
    - LocalDate fechaCaducidadCarnet
    + boolean validarDNI()
    + int getEdad()
}
@enduml