@startuml
abstract class Vehiculo {
    - {final} String matricula
    - String marca
    - String modelo
    - int kilometraje
    - double precio
    - LocalDate fechaFabricacion
    - Persona propietario
    + {abstract} double calcularDepreciacion()
    + double calcularRiesgo(int experienciaConductor)
    + String getMatricula()
    + void setPropietario(Persona propietario)
}
@enduml
